# config
logo: /images/yamaguchi.png
keywords: "Yuka Takahashi, yamaguchi.txt, yamaguchi, CTF, pwn, mama, programming, FPGA, raspberry pi"
menu:
  Home: /
  About me: /about
  Works: /works
  Articles: /articles
  Contact: /contact

# Content
excerpt_link: Read more

# Miscellaneous
google_analytics:
